### ISSUE TITLE
Support NSDate with custom mapped function

### ISSUE THREAD

**Issue by chriscombs** [nodes-ios/Serializable#17]
Currently has a `Date` class, but would be nice to support `NSDate` natively.

**Comment by chriscombs** [comment]
After investigating, we'll need a separate mapped function for it

**Comment by kasperwelner** [comment]
This has been added by @chriscombs and @jakobmygind

**Comment by dominik-hadl** [comment]
It's missing documentation though...

**Comment by kasperwelner** [comment]
Didn’t Chris add it? 

## 

Kasper Welner
iOS Lead

Nodes - We build awesome digital stuff

Mobile:  +45 41 62 60 20
Web:   http://www.nodes.dk http://www.nodes.dk/

**Comment by dominik-hadl** [comment]
I don't see any in the source. Also, there's some things that make the generics in the code useless.

The new `mapped` function overload looks like this:

```
public func mapped<T: HexInitializable>(dictionary: NSDictionary?, key: String) -> T? {
        guard let dict = dictionary else {
            return nil
        }

        let sourceOpt = dict[key]

        if let source = sourceOpt as? String where source.isEmpty == false {
            return UIColor.colorWithHexString(source) as? T
        }

        return nil
    }
```

It expects an object which adheres to `HexInitializable` but then returns plain `UIColor.colorWithHexString`, instead of properly using that protocol to instantiate a generic object. There were also some formatting issues, I'll submit a PR in a few seconds for this.

**Comment by kasperwelner** [comment]
Nice thx! 

## 

Kasper Welner
iOS Lead

Nodes - We build awesome digital stuff

Mobile:  +45 41 62 60 20
Web:   http://www.nodes.dk http://www.nodes.dk/

**Comment by dominik-hadl** [comment]
Wtf.. Apparently, I'm tired. I was looking and talking about custom mapped overload for `UIColor`. There is no overload for `NSDate` so far.

**Comment by dominik-hadl** [comment]
Just started on this, I will create a PR with support for `NSDate` with no need for wrapper object tomorrow morning.
